name: Deploy

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build"]
    branches: [main]
    types: [completed]

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    env:
      NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: npm
      - name: Setup pages
        uses: actions/configure-pages@v2
        with:
          static_site_generator: next
      - name: Restore next cache
        working-directory: examples/nextjs
        uses: actions/cache@v3
        with:
          path: .next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-
      - name: Restore rotion cache
        working-directory: examples/nextjs
        uses: actions/cache@v3
        with:
          path: |
            .cache
            public/images
          key: rotion
          restore-keys: rotion
      - name: Install dependencies
        working-directory: examples/nextjs
        run: npm ci
      - name: Build and Export
        working-directory: examples/nextjs
        run: |
          npm run build
      - name: Upload artifact
        working-directory: examples/nextjs
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Deploy to github pages
        id: deployment
        uses: actions/deploy-pages@v1
